services:
  postgres:
    image: postgres:16
    container_name: minihittegods-postgres
    environment:
      POSTGRES_DB: minihittegods
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - minihittegods_data:/var/lib/postgresql/data


volumes:
  minihittegods_data: